const state = { selected: null, starred: false, dashboard: null, activeSector: '', visibleLimit: 100 };
const titles = { overview:'市场驾驶舱', agents:'Agent 协作台', factors:'因子实验室', candidates:'候选选股', portfolio:'组合与风控', backtest:'回测实验', audit:'复盘审计' };
const copies = { factors:'因子目录来自最近一次 Agent 真实挖掘结果，并展示组合候选。', candidates:'候选池按真实因子横截面标准化排序，所有价格和评分来自当前数据请求。', portfolio:'组合模块等待账户与持仓数据接入；当前只展示真实行情研究结果。', backtest:'回测实验读取最新因子结果，测试单因子、二因子和三因子排列组合。', audit:'审计模块等待决策日志服务接入；当前不展示任何虚构成交。' };
const toast = (message) => { document.getElementById('toastText').textContent = message; document.getElementById('toast').classList.add('show'); window.clearTimeout(window.__toast); window.__toast = window.setTimeout(() => document.getElementById('toast').classList.remove('show'), 2600); };
const fmtPct = (value) => `${value >= 0 ? '+' : ''}${Number(value).toFixed(2)}%`;
const fmtPrice = (value) => value ? `¥ ${Number(value).toFixed(2)}` : '—';
const signed = (value) => `${value >= 0 ? '+' : ''}${Number(value).toFixed(1)}`;
const factorScore = (value) => 50 + 12 * (Number(value) || 0);
const pctClass = (value) => Number(value) >= 0 ? 'up' : 'negative-text';
function setText(id, value) { const el = document.getElementById(id); if (el) el.textContent = value; }
function setLoading(message) { document.querySelectorAll('.data-loading').forEach((el) => { el.textContent = message; }); }
function renderTechUniverse(data) {
  const universe=data.tech_universe||{}, selected=new Set(universe.selected_sectors||[]), target=document.getElementById('techSectorSelector');
  if(!target)return;
  target.innerHTML=(universe.sectors||[]).map((sector)=>`<label class="tech-sector-option"><input type="checkbox" value="${sector.key}" ${selected.has(sector.key)?'checked':''}><span>${sector.name}<b>${sector.count||0}</b></span></label>`).join('');
  setText('universeMeta',`${data.universe_size||0} 只真实科技股 · ${universe.source||'东方财富行业与概念分类'} · 排除科创板与 ST`);
  renderSectorRankingTabs(data);
}
function stocksForActiveSector(data) { return state.activeSector ? data.stocks.filter((stock)=>(stock.tech_sectors||[]).includes(state.activeSector)) : data.stocks; }
function renderSectorRankingTabs(data) { const target=document.getElementById('sectorRankingTabs'), sectors=(data.tech_universe?.sectors||[]).filter((item)=>item.count>0 && (data.tech_universe?.selected_sectors||[]).includes(item.key)); if(!target)return; const buttons=[{key:'',name:'科技总榜',count:data.universe_size||0},...sectors]; target.innerHTML=buttons.map((item)=>`<button class="ranking-tab ${state.activeSector===item.key?'active':''}" data-sector="${item.key}">${item.name}<span>${item.count}</span></button>`).join(''); target.querySelectorAll('.ranking-tab').forEach((button)=>button.addEventListener('click',()=>{state.activeSector=button.dataset.sector||'';state.selected=null;state.visibleLimit=100;renderSectorRankingTabs(data);renderCandidates(data);toast(`已切换：${button.childNodes[0].textContent.trim()}`);})); }
function renderStrategySelect(data) { const run=data.backtest_factor_run, select=document.getElementById('strategySelect'); if(!select||!run)return; select.innerHTML='<option value="">选择一个回测策略</option>'+run.results.map((item,index)=>`<option value="${item.factors.join(',')}">${item.kind} · ${item.names.join(' + ')}</option>`).join(''); setText('activeStrategyName',data.agent_selection?.name || '请选择回测策略'); setText('activeStrategyRule',data.agent_selection ? `${data.agent_selection.selected_count} 只候选 · 只持有 Top 3` : '请从回测实验或下方菜单选择策略'); }
function renderMarket(data) {
  renderStrategySelect(data);
  renderTechUniverse(data);
  const hs = data.market.hs300, cyb = data.market.cyb;
  setText('hs300Pct', hs ? fmtPct(hs.pct) : '无数据'); setText('hs300Price', hs ? fmtPrice(hs.price) : '接口未返回');
  setText('cybPct', cyb ? fmtPct(cyb.pct) : '无数据'); setText('cybPrice', cyb ? fmtPrice(cyb.price) : '接口未返回');
  document.getElementById('hs300Pct').className = hs ? pctClass(hs.pct) : ''; document.getElementById('cybPct').className = cyb ? pctClass(cyb.pct) : '';
  const quoteClock = data.quote_time ? `${data.quote_time.slice(0,4)}-${data.quote_time.slice(4,6)}-${data.quote_time.slice(6,8)} ${data.quote_time.slice(8,10)}:${data.quote_time.slice(10,12)}:${data.quote_time.slice(12,14)}` : (data.generated_at ? data.generated_at.slice(11) : '后台刷新中'); setText('breadth', `${data.breadth.up} / ${data.breadth.down}`); setText('dataSource', data.source_label || data.source); setText('dataTimestamp', `${data.latest_date || '—'} · ${quoteClock}`); setText('scanTimestamp', `${quoteClock} 更新`); setText('systemStatus', data.refreshing ? '后台刷新中' : '系统健康'); setText('systemSync', `${data.source_label || data.source} ${quoteClock}`); setText('marketClockLabel', '行情时间'); setText('marketClockTime', quoteClock);
  const avg = [hs?.pct, cyb?.pct].filter((v) => typeof v === 'number'), positive = avg.length && avg.reduce((a,b) => a+b, 0) / avg.length >= 0;
  setText('regimeText', avg.length ? (positive ? '结构性偏多' : '结构性偏弱') : '指数无数据'); setText('regimeConfidence', avg.length ? `${Math.min(99, Math.round(50 + Math.abs(avg.reduce((a,b) => a+b, 0) / avg.length) * 12))}%` : '—');
  setText('regimeNote', `数据截止 ${data.latest_date || '—'}；来源：${data.source_label || data.source}。`); document.querySelector('.page-heading p').textContent = `${data.universe_size} 只真实科技股完成扫描，科创板 688/689 已排除。`; document.querySelector('.nav-badge').textContent = data.universe_size;
  document.querySelector('.market-strip-main .regime-dot').style.background = positive ? '#4ca67d' : '#be6c64';
  const counts = [data.stocks.length, data.stocks.filter((s) => s.status === '可建仓').length, data.stocks.filter((s) => s.status === '等待触发').length, data.stocks.filter((s) => s.factors.volatility20 > .8).length]; document.querySelectorAll('.filter-button span').forEach((el, i) => { el.textContent = counts[i]; });
}
const agentBlueprint={
  '研究研发组':[['factor_hypothesis','因子假设 Agent'],['factor_developer','因子开发 Agent'],['model_research','模型研究 Agent']],
  '市场情报组':[['market_regime','市场状态 Agent'],['industry_chain','科技产业链 Agent'],['event_news','事件新闻 Agent']],
  '实验验证组':[['experiment_design','实验设计 Agent'],['backtest','回测 Agent'],['challenger','Challenger Agent']],
  '决策执行组':[['portfolio_manager','组合经理 Agent'],['risk_execution','风控执行 Agent']]
};
const safe=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function renderAgentCollaboration(data) {
  const run=data.multi_agent_run, allAgents=run?.agents||[], byId=Object.fromEntries(allAgents.map((item)=>[item.id,item])), waiting={status:'等待',summary:'等待首席研究 Agent 调度',evidence:[]};
  const chief=byId.chief||{...waiting,name:'首席研究 Agent',role:'制定任务、检查依赖并签发最终研究结论'};
  const decision=run?.decision||{}, holdings=(decision.holdings||[]).slice(0,3), completed=run&&['等待人工批准','阻断'].includes(run.status);
  setText('agentMission',run?.mission||'十二 Agent、四团队量化研究会签');
  setText('agentMissionMeta',run?`运行 ${run.run_id} · 版本 ${run.version}`:'因子假设由 Codex 推理；数值由确定性代码计算');
  setText('agentResearchDate',run?.data_date||data.latest_date||'—'); setText('agentUniverseCount',`${run?.universe_size||data.universe_size||0} 只`); setText('agentLoopState',run?.status||'未运行'); setText('agentRunTime',run?.updated_at||'等待运行记录');
  const chiefTone=chief.status==='失败'||chief.status==='阻断'?'risk':chief.status==='运行中'?'running':chief.status==='等待'?'idle':'complete';
  document.getElementById('agentChief').innerHTML=`<div class="agent-chief-avatar">CIO</div><div><span>首席研究 Agent</span><strong>${safe(chief.summary)}</strong><small>${safe(chief.role||'制定任务、检查依赖并签发最终研究结论')}</small></div><b class="agent-status ${chiefTone}">${safe(chief.status)}</b>`;
  document.getElementById('agentTeams').innerHTML=Object.entries(agentBlueprint).map(([team,members],teamIndex)=>`<section class="agent-team-column"><header><span>0${teamIndex+1}</span><div><strong>${team}</strong><small>${members.length} AGENTS</small></div></header><div class="agent-team-flow">${members.map(([id,name],index)=>{const item=byId[id]||{...waiting,name};const tone=['失败','阻断'].includes(item.status)?'risk':['警告','降级','数据受限'].includes(item.status)?'warn':item.status==='运行中'?'running':item.status==='完成'?'complete':'idle';const evidence=(item.evidence||[])[0]||item.role||'等待上游任务';return `<article class="agent-work-node ${tone}" data-agent-id="${id}"><div class="agent-work-top"><span>${String(index+1).padStart(2,'0')}</span><b>${safe(item.status)}</b></div><strong>${safe(item.name||name)}</strong><p>${safe(item.summary)}</p><small>${safe(evidence)}</small>${item.artifact?`<code>${safe(item.artifact)}</code>`:''}</article>`}).join('<i class="agent-flow-arrow">↓</i>')}</div></section>`).join('');
  const strategy=(decision.strategy||[]).join(' + ');
  setText('agentDecisionTitle',strategy?`组合经理：${strategy}`:'等待十二 Agent 会签'); setText('agentDecisionRule',holdings.length?'最多3只、等权研究组合；Challenger 未批准实盘，必须人工确认。':'没有完成全部真实验证前，组合经理不会输出股票。');
  document.getElementById('agentTop3').innerHTML=holdings.length?holdings.map((stock,index)=>`<button class="agent-pick" data-symbol="${safe(stock.code)}"><span>0${index+1}</span><div><strong>${safe(stock.name)}</strong><small>${safe(stock.code)}</small></div><b>查看 →</b></button>`).join(''):`<div class="agent-empty-decision">${run?.status==='阻断'?'会签已阻断':'等待组合经理输出'}</div>`;
  document.querySelectorAll('.agent-pick').forEach((button)=>button.addEventListener('click',()=>{document.querySelector('[data-view="overview"]').click();selectStock(button.dataset.symbol);}));
  const artifacts=allAgents.filter((item)=>item.artifact).slice().reverse();
  document.getElementById('agentEvidence').innerHTML=artifacts.length?artifacts.map((item,index)=>`<div class="agent-evidence-row"><span>${String(artifacts.length-index).padStart(2,'0')}</span><div><strong>${safe(item.name)}</strong><small>${safe(item.summary)}</small><code>${safe(item.artifact)}</code></div></div>`).join(''):'<div class="data-loading">运行后会为每个 Agent 写入独立 JSON 产物</div>';
  const warnings=run?.warnings||[]; setText('criticCount',`${warnings.length} 项`);
  document.getElementById('agentCritiques').innerHTML=warnings.length?warnings.map((text,index)=>`<div class="agent-critique-row ${index===0?'risk':'warn'}"><span>${index===0?'!':'△'}</span><div><strong>${index===0?'Challenger 意见':'数据或执行限制'}</strong><small>${safe(text)}</small></div></div>`).join(''):'<div class="data-loading">尚未产生会签警告</div>';
  const button=document.getElementById('agentRunButton'); button.disabled=Boolean(run&&!completed&&run.status==='运行中'); button.innerHTML=button.disabled?'十二 Agent 运行中…':'运行十二 Agent 闭环 <span>↗</span>';
}
async function pollAgentCouncil() {
  for(let attempt=0;attempt<360;attempt++){
    const response=await fetch('/api/agents',{cache:'no-store'}), payload=await response.json();
    if(payload.run){state.dashboard.multi_agent_run=payload.run;renderAgentCollaboration(state.dashboard);}
    if(!payload.running)return payload.run;
    await new Promise((resolve)=>setTimeout(resolve,1500));
  }
  throw new Error('十二 Agent 运行超时，请刷新查看已落盘状态');
}
async function runAgentCollaboration() {
  const button=document.getElementById('agentRunButton'); button.disabled=true;button.textContent='正在启动十二 Agent…';
  try {
    const response=await fetch('/api/agents/run',{method:'POST'}), payload=await response.json();if(!response.ok||payload.error)throw new Error(payload.error||'启动失败');
    toast('十二 Agent、四团队已启动'); await pollAgentCouncil();
    const dashboardResponse=await fetch('/api/dashboard',{cache:'no-store'}), dashboard=await dashboardResponse.json();if(!dashboardResponse.ok||dashboard.error)throw new Error(dashboard.error||'结果读取失败');
    state.dashboard=dashboard;renderMarket(dashboard);renderCandidates(dashboard);renderFactorLab(dashboard);renderBacktest(dashboard);renderAgentCollaboration(dashboard);toast(`十二 Agent 会签完成：${dashboard.multi_agent_run?.status||'已落盘'}`);
  } catch(error){toast(`Agent 会签未完成：${error.message}`);}
  finally{button.disabled=false;button.innerHTML='运行十二 Agent 闭环 <span>↗</span>';}
}
function rowTemplate(stock, index, useCombo=false) {
  const colors = ['red', 'orange', 'blue', 'purple'], f = stock.factors;
  const comboTags = useCombo ? (stock.agent_combo_breakdown || []).map((item) => `<span class="factor ${item.score >= 50 ? 'positive' : 'negative'}">${item.name} ${item.direction} ${Number(item.score).toFixed(0)}</span>`).join('') : '';
  const tags = comboTags || `<span class="factor ${f.momentum20 >= 0 ? 'positive' : 'negative'}">动量 ${signed(factorScore(f.momentum20)-50)}</span><span class="factor ${f.trend >= 0 ? 'positive' : 'negative'}">趋势 ${signed(factorScore(f.trend)-50)}</span><span class="factor ${f.volume_ratio >= 1 ? 'positive' : 'neutral'}">量比 ${Number(f.volume_ratio).toFixed(2)}x</span>`;
  const statusClass = stock.status === '可建仓' ? 'ready' : stock.status === '等待触发' ? 'wait' : 'watch';
  const displayScore = useCombo ? (stock.agent_combo_score ?? stock.score) : stock.score;
  return `<div class="table-row candidate-row ${index === 0 ? 'selected' : ''}" data-symbol="${stock.code}"><div class="stock-cell"><div class="stock-logo ${colors[index % colors.length]}">${stock.initial}</div><div><strong>${stock.name}</strong><small>${stock.code} · ${stock.industry||stock.market}</small></div></div><div class="score-cell"><strong>${Number(displayScore).toFixed(1)}</strong><div class="score-track"><span style="width:${Number(displayScore).toFixed(1)}%"></span></div></div><div class="factor-cell">${tags}</div><div><span class="status ${statusClass}">${stock.status}</span></div><div class="chevron">→</div></div>`;
}
function renderCandidates(data) {
  const sectorStocks=stocksForActiveSector(data), useSelection=Boolean(data.agent_selection&&!state.activeSector), shortlist=useSelection?sectorStocks.filter((stock)=>stock.agent_combo_selected).sort((a,b)=>b.agent_combo_score-a.agent_combo_score):sectorStocks;
  const visible=useSelection?shortlist:shortlist.slice(0,state.visibleLimit), tableTitle=useSelection?'回测策略最新 Top 3':(state.activeSector?'细分板块综合排名':'科技总榜'); const table = document.getElementById('candidateTable'); table.innerHTML = `<div class="table-row table-header"><span>${tableTitle}</span><span>综合评分</span><span>真实因子</span><span>交易状态</span><span></span></div>${visible.map((stock,index)=>rowTemplate(stock,index,useSelection)).join('')}`;
  const loadMore=document.getElementById('loadMore'); loadMore.disabled=useSelection||visible.length>=shortlist.length; loadMore.innerHTML=useSelection?`当前回测策略只保留 ${shortlist.length} 只核心候选 <span>↗</span>`:`已显示 ${visible.length} / ${shortlist.length} 只真实科技股 ${visible.length<shortlist.length?'<span>继续加载 ↗</span>':''}`; loadMore.onclick=()=>{state.visibleLimit+=100;renderCandidates(data);};
  table.querySelectorAll('.candidate-row').forEach((row) => row.addEventListener('click', () => selectStock(row.dataset.symbol))); selectStock(visible[0]?.code);
}
function sparklinePaths(stock) { const points = stock.klines || []; if (points.length < 2) return { area:'', line:'' }; const closes = points.map((x) => x.close), min = Math.min(...closes), max = Math.max(...closes), span = max - min || 1; const coords = closes.map((v, i) => `${(i/(closes.length-1))*460},${110 - ((v-min)/span)*98}`).join(' L'); return { line:`M${coords}`, area:`M${coords} L460,120 L0,120Z` }; }
function renderInsight(stock) {
  if (!stock) return; state.selected = stock.code; document.querySelectorAll('.candidate-row').forEach((row) => row.classList.toggle('selected', row.dataset.symbol === stock.code));
  setText('selectedName', `${stock.name} ${stock.code}`); setText('selectedPrice', fmtPrice(stock.price)); setText('selectedPct', fmtPct(stock.pct)); setText('selectedScore', Number(stock.agent_combo_score??stock.score).toFixed(1)); document.getElementById('selectedPct').className = pctClass(stock.pct);
  document.getElementById('signalMeta').innerHTML = `<span class="status ${stock.status === '可建仓' ? 'ready' : stock.status === '等待触发' ? 'wait' : 'watch'}">${stock.status}</span><span class="meta-sep">·</span><span>${stock.source_label || '真实日线因子'} · K线截止 ${stock.last_date || '—'}</span>`; setText('confidenceLabel', stock.score >= 70 ? '高' : stock.score >= 55 ? '中' : '低'); const qt = stock.quote_time ? `${stock.quote_time.slice(8,10)}:${stock.quote_time.slice(10,12)}:${stock.quote_time.slice(12,14)}` : ''; setText('priceCaption', `${stock.source_label || '真实行情'}${qt ? ` · ${qt}` : ''}`);
  const paths = sparklinePaths(stock); document.getElementById('sparkPath').setAttribute('d', paths.line); document.getElementById('sparkArea').setAttribute('d', paths.area); const k = stock.klines || []; const labels = [k[0]?.date, k[Math.floor(k.length/3)]?.date, k[Math.floor(k.length*2/3)]?.date, k[k.length-1]?.date].map((x) => x ? x.slice(5) : '—'); document.getElementById('chartLabels').innerHTML = labels.map((x) => `<span>${x}</span>`).join('');
  const f = stock.factors, comboRows = (stock.agent_combo_breakdown || []).map((item) => `<div class="agent-row"><div class="agent-avatar quant">F</div><div><strong>${item.name}</strong><small>${item.direction}使用 · 截面排名分 ${Number(item.score).toFixed(1)}</small></div><span class="agent-score ${item.score >= 50 ? 'good' : 'caution'}">${Number(item.score).toFixed(1)}</span></div>`).join(''); document.getElementById('agentList').innerHTML = `<div class="agent-row"><div class="agent-avatar data">D</div><div><strong>组合选股 Agent</strong><small>${stock.agent_combo_selected ? '当前进入 Top 3 核心候选' : '当前未进入 Top 3'} · 组合分数 ${Number(stock.agent_combo_score || 0).toFixed(1)}</small></div><span class="agent-score ${stock.agent_combo_selected ? 'good' : 'caution'}">${stock.agent_combo_selected ? '入选' : '观察'}</span></div>${comboRows}<div class="agent-row"><div class="agent-avatar data">D</div><div><strong>数据质量 Agent</strong><small>${stock.last_date ? `日线已更新至 ${stock.last_date}` : '无日线数据'}</small></div><span class="agent-score good">${stock.last_date ? '通过' : '阻断'}</span></div><div class="agent-row"><div class="agent-avatar bear">R</div><div><strong>基础风险因子</strong><small>20D 年化波动 ${fmtPct(f.volatility20*100)}</small></div><span class="agent-score caution">${signed(factorScore(f.volatility20)-50)}</span></div>`; renderFactorMap(stock); renderChecks(stock);
}
function renderFactorMap(stock) { const f = stock.factors, combo = stock.agent_combo_breakdown || [], items = combo.length ? combo.map((item) => [item.key, `${item.name} · ${item.direction}`, 'Agent 组合截面排名', item.score]) : [['momentum20','20D 动量','return / cross-sectional',factorScore(f.momentum20)],['trend','5/20D 趋势','moving-average spread',factorScore(f.trend)],['volume_ratio','5/20D 量比','volume confirmation',factorScore(f.volume_ratio-1)],['volatility20','20D 年化波动','risk penalty',50-factorScore(f.volatility20)+50]]; document.getElementById('factorTimestamp').textContent = stock.last_date || '—'; document.getElementById('factorModel').textContent = combo.length ? 'Agent Factor Ensemble v1' : 'Technical Cross-Section v0.1'; document.getElementById('factorMap').innerHTML = items.map(([, label, desc, score]) => { const positive = score >= 50, width = Math.max(5, Math.min(100, score)); return `<div class="factor-map-row"><div class="factor-name">${label}<small>${desc}</small></div><div class="factor-bar"><span class="${positive ? 'positive-bar' : 'negative-bar'}" style="width:${width}%"></span></div><strong class="${positive ? 'positive-text' : 'negative-text'}">${Number(score).toFixed(1)}</strong></div>`; }).join(''); }
function renderChecks(stock) { const checks = [{ok:!!stock.last_date,title:'数据时点有效',note:stock.last_date ? `最后日线：${stock.last_date}` : '没有返回日线数据'},{ok:stock.price>0 && stock.volume>0,title:'行情字段完整',note:stock.price>0 && stock.volume>0?'价格与成交量已返回':'价格或成交量为空'},{ok:stock.factors.volatility20<.8,title:'波动率约束',note:`20D 年化波动 ${fmtPct(stock.factors.volatility20*100)}`},{ok:false,title:'人工确认',note:'真实交易计划尚未确认'}], passed = checks.filter((x)=>x.ok).length; setText('riskSummary',`${passed} / ${checks.length} 已通过`); document.getElementById('checkList').innerHTML = checks.map((x,i)=>`<div class="check-row"><span class="check-icon ${x.ok?'pass':i===3?'block':'warn'}">${x.ok?'✓':i===3?'×':'!'}</span><div><strong>${x.title}</strong><small>${x.note}</small></div>${i===3?'<button class="confirm-button" id="confirmButton">去确认</button>':`<span class="check-tag ${x.ok?'pass-text':'warn-text'}">${x.ok?'通过':'注意'}</span>`}</div>`).join(''); document.getElementById('confirmButton').addEventListener('click',(event)=>{event.currentTarget.textContent='已确认';event.currentTarget.style.color='#438368';event.currentTarget.style.borderColor='#9ed1b5';event.currentTarget.style.background='#f2fbf5';toast('仅记录研究确认，不会下单');}); }
function renderFactorLab(data) {
  const catalog = data.factor_lab_agent_catalog || data.factor_catalog || [], visibleCatalog = catalog.slice(0, 8), sample = state.selected ? data.stocks.find((s) => s.code === state.selected) : data.stocks[0], agent = data.agent_factor_run;
  setText('labModelName', data.factor_model?.name || 'Technical Cross-Section'); setText('labModelNote', agent?.stale ? `${data.source_label || data.source} · 历史结果，当前股池已变化` : `${data.source_label || data.source} · 最近一次 Agent 研究结果`); setText('labFactorCount', catalog.length); setText('labLatestDate', sample?.last_date || data.latest_date || '—'); setText('labSource', data.source_label || data.source);
  document.getElementById('factorCatalog').innerHTML = visibleCatalog.map((factor, index) => { const isAgent = factor.category === 'Agent 挖掘'; const value = sample?.factors?.[factor.key]; const display = isAgent ? `${factor.status || '研究中'} · ${factor.direction || '待定'}` : factor.key === 'volume_ratio' ? `${Number(value || 0).toFixed(2)}x` : fmtPct(Number(value || 0) * 100); const extra = isAgent ? `Rank IC ${Number(factor.rank_ic || 0).toFixed(4)} · ICIR ${Number(factor.icir || 0).toFixed(3)}` : `权重 ${Math.round((factor.weight || 0)*100)}%`; return `<div class="factor-catalog-row"><div class="factor-index">${String(index+1).padStart(2,'0')}</div><div class="factor-catalog-copy"><div><strong>${factor.name}</strong><span class="factor-category">${factor.category}</span></div><p>${factor.description}</p><code>${factor.formula}</code></div><div class="factor-catalog-value"><strong>${display}</strong><small>${extra}</small></div></div>`; }).join('');
  document.getElementById('formulaGrid').innerHTML = visibleCatalog.map((factor) => `<div class="formula-chip"><span>${factor.name}</span><code>${factor.formula}</code></div>`).join('') + (agent ? `<div class="mine-warning">展示前 8 个候选，共 ${catalog.length} 个已入库；本次 Agent 搜索空间 ${agent.search_space_size} 个公式。</div>` : '');
}
function renderBacktest(data) { const run = data.backtest_factor_run; if (!run) return; setText('backtestInput', `${run.candidate_count} 个候选因子`); setText('backtestUniverse', `${run.universe_name||'科技股池'} · ${run.confirmation_universe||0} 只`); setText('backtestUniverseNote',(run.selected_sectors||[]).join(' / ')||'排除科创板 688/689'); setText('backtestCount', run.combination_count); setText('backtestDate', `${run.data_date || '—'} · ${run.generated_at || ''}`); setText('backtestCost', `${run.cost_bps}bp`); const groups = ['1 因子','2 因子组合','3 因子组合']; const renderItem = (item,index) => { const r=item.result||{}, holdings=(r.latest_holdings||[]).slice(0,3).map((x)=>`${x.name}(${x.code})`).join('、'), formula=item.names.map((name,i)=>`${name}（${item.directions?.[i] || '待定'}）`).join(' × '), annualLabel=r.annualization_reliable?'年化':'年化参考'; return `<div class="mine-result-row backtest-selectable" data-factors="${item.factors.join(',')}" title="点击将该策略的最新 3 只股票同步到候选池"><strong>#${item.rank || index+1} ${item.kind}</strong><span>${r.status || '—'} · ${r.holding_count || 0} 只等权持仓 · 点击选择</span><small class="backtest-factor-line">${formula}</small><small>累计 ${fmtPct(Number(r.cumulative_return||0)*100)} · ${annualLabel} ${fmtPct(Number(r.annual_return||0)*100)} · Sharpe ${Number(r.sharpe||0).toFixed(2)} · 最大回撤 ${fmtPct(-Number(r.max_drawdown||0)*100)} · 胜率 ${fmtPct(Number(r.win_rate||0)*100)} · ${r.days||0} 天<br>最新 3 只：${holdings || '—'}</small></div>`; }; document.getElementById('backtestResults').innerHTML = `<div class="mine-warning"><strong>排名依据</strong>：${run.ranking_metric || '成本后 Sharpe'}。短样本优先看累计收益和回撤，年化只作参考。<br><strong>收益口径</strong>：T 日收盘生成信号，T+1 收盘建仓，T+2 收盘退出；每只 1/3，扣除 15bp × 换手率。<br><strong>股池口径</strong>：只在所选科技细分中排名，硬排除科创板 688/689。点击结果可同步最新 3 只股票。</div>` + groups.map((group) => { const items=run.results.filter((item)=>item.kind===group); return `<section class="backtest-group"><h3>${group}<small>${items.length} 个结果</small></h3>${items.map(renderItem).join('')}</section>`; }).join('') + `<div class="mine-warning">${run.warning}</div>`; document.querySelectorAll('.backtest-selectable').forEach((row)=>row.addEventListener('click',()=>selectBacktestStrategy(row.dataset.factors.split(',')))); }
async function selectBacktestStrategy(factors) { try { const response=await fetch('/api/backtest/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factors})}), data=await response.json(); if(!response.ok||data.error)throw new Error(data.error||'策略选择失败'); const selected=new Set(data.selection.top_codes); state.dashboard.agent_selection=data.selection; state.dashboard.stocks.forEach((stock)=>{const hit=data.stocks.find((item)=>item.code===stock.code);stock.agent_combo_selected=selected.has(stock.code);if(hit){stock.agent_combo_score=hit.agent_combo_score;stock.agent_combo_breakdown=hit.agent_combo_breakdown;stock.agent_combo_factors=factors;}}); renderCandidates(state.dashboard); toast(`已选择策略：${data.selection.name}，候选池同步 3 只`); } catch(error) { toast(`策略选择失败：${error.message}`); } }
async function runBacktest() { const target=document.getElementById('backtestResults'); target.innerHTML='<div class="data-loading">正在对最新因子做单因子、二因子、三因子真实回测…</div>'; try { const response=await fetch('/api/backtest',{method:'POST'}), data=await response.json(); if(!response.ok||data.error)throw new Error(data.error||'回测失败'); state.dashboard.backtest_factor_run=data; renderBacktest(state.dashboard); toast(`组合回测完成：${data.combination_count} 个组合`); } catch(error) { target.innerHTML=`<div class="data-error">真实回测未完成：${error.message}</div>`; toast('真实组合回测未完成'); } }
async function applyTechUniverse() {
  const sectors=[...document.querySelectorAll('#techSectorSelector input:checked')].map((input)=>input.value), button=document.getElementById('applyUniverseButton');
  if(!sectors.length)return toast('至少选择一个科技细分板块');
  button.disabled=true; button.textContent='重建中…'; toast('正在重建真实科技股池');
  try {
    const response=await fetch('/api/universe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sectors})}), data=await response.json();
    if(!response.ok||data.error)throw new Error(data.error||'股池更新失败');
    state.dashboard=data; state.selected=null; renderMarket(data); renderCandidates(data); renderFactorLab(data);
    document.getElementById('backtestResults').innerHTML='<div class="mine-warning">科技股池已变化。请先重新运行 Agent 因子闭环，再运行组合回测；系统不会沿用旧股池结果。</div>';
    setText('backtestInput','等待重新挖掘'); setText('backtestCount','—');
    toast(`科技股池已更新：${data.universe_size} 只，已排除科创板`);
  } catch(error) { toast(`股池更新失败：${error.message}`); }
  finally { button.disabled=false; button.textContent='更新股池'; }
}
function selectStock(code) { const stock = state.dashboard?.stocks.find((item) => item.code === code); if (stock) { renderInsight(stock); if (state.dashboard) renderFactorLab(state.dashboard); toast(`已切换至 ${stock.name} 的真实因子信号`); } }
async function runFactorMining() {
  const target = document.getElementById('mineResults');
  target.innerHTML = '<div class="data-loading">正在使用真实历史 K 线计算 Rank IC 与分层收益…</div>';
  try {
    const response = await fetch('/api/mine/agent', {method:'POST'}), data = await response.json();
    if (!response.ok || data.error) throw new Error(data.error || '挖掘接口失败');
    const validation = data.validation || {}, ranked = (validation.results || []).filter((item) => item.mean_rank_ic !== undefined).slice(0, 8);
    target.innerHTML = `<div class="mine-result-meta">搜索空间 ${data.search_space_size || validation.candidate_count} 个公式 · ${validation.usable_stocks} 只股票 · ${validation.history_bars || 0} 个共同历史样本 · 数据截止 ${validation.data_date || '—'}</div><div class="mine-agent-stages">${(data.stages || []).map((stage) => `<span>${stage.name}：${stage.status}</span>`).join('')}</div>${ranked.map((item) => { const bt=item.backtest||{}; return `<div class="mine-result-row"><strong>${item.name}</strong><span>${item.gate || item.status} · ${item.direction || '待定'}使用</span><small>${item.hypothesis || item.formula || ''}<br>Rank IC ${Number(item.mean_rank_ic).toFixed(4)} · ICIR ${Number(item.icir).toFixed(2)} · 方向调整后多空 ${fmtPct(Number(item.effective_long_short ?? item.mean_long_short) * 100)} · 回测年化 ${fmtPct(Number(bt.annual_return || 0) * 100)} · 回测回撤 ${fmtPct(Number(bt.max_drawdown || 0) * 100)}</small></div>`; }).join('')}<div class="mine-warning">${data.feedback}</div>`;
    toast(`Agent 闭环完成：${validation.candidate_count} 个公式已验证`);
  } catch (error) {
    target.innerHTML = `<div class="data-error">真实挖掘未完成：${error.message}</div>`;
    toast('真实因子挖掘未完成');
  }
}
async function loadDashboard() { setLoading('正在读取真实行情与日线 K 线…'); try { const response = await fetch('/api/dashboard',{cache:'no-store'}), data = await response.json(); if (!response.ok || data.error) throw new Error(data.error || '接口请求失败'); state.dashboard = data; renderMarket(data); renderCandidates(data); renderFactorLab(data); renderAgentCollaboration(data); toast(`已接入${data.source_label || '真实行情'} · ${data.latest_date || '无最新交易日'}`); } catch (error) { document.getElementById('candidateTable').innerHTML = `<div class="data-error">真实数据接口不可用：${error.message}<br><small>页面不会使用模拟数据。请确认通过 server.py 启动，并检查网络。</small></div>`; document.getElementById('agentList').innerHTML='<div class="data-error">无真实数据，不生成分析结论。</div>'; document.getElementById('factorMap').innerHTML='<div class="data-error">无真实数据，不计算因子。</div>'; document.getElementById('factorCatalog').innerHTML='<div class="data-error">无真实数据，不展示因子目录。</div>'; document.getElementById('formulaGrid').innerHTML='<div class="data-error">无真实数据，不展示公式。</div>'; document.getElementById('agentTeams').innerHTML='<div class="data-error">无真实数据，十二 Agent 协作已阻断。</div>'; document.getElementById('checkList').innerHTML='<div class="data-error">无真实数据，不允许进入交易确认。</div>'; setText('dataSource','未连接'); setText('systemStatus','数据阻断'); setText('systemSync','未同步'); setText('marketClockTime','未连接'); toast('真实数据连接失败，已阻断模拟内容'); } }
document.querySelectorAll('.nav-item').forEach((button)=>button.addEventListener('click',()=>{const view=button.dataset.view;document.querySelectorAll('.nav-item').forEach((item)=>item.classList.toggle('active',item===button));setText('viewTitle',titles[view]);const overview=document.getElementById('overviewView'),agents=document.getElementById('agentCollabView'),factorLab=document.getElementById('factorLabView'),backtest=document.getElementById('backtestView'),placeholder=document.getElementById('placeholderView');overview.hidden=view!=='overview';agents.hidden=view!=='agents';factorLab.hidden=view!=='factors';backtest.hidden=view!=='backtest';placeholder.hidden=!['candidates','portfolio','audit'].includes(view);if(view==='agents'&&state.dashboard)renderAgentCollaboration(state.dashboard);if(view==='factors'&&state.dashboard)renderFactorLab(state.dashboard);if(view==='backtest'&&state.dashboard)renderBacktest(state.dashboard);if(!placeholder.hidden){setText('placeholderTitle',titles[view]);setText('placeholderCopy',copies[view]);}}));
document.getElementById('starButton').addEventListener('click',(event)=>{if(!state.selected)return toast('暂无真实候选可收藏');state.starred=!state.starred;event.currentTarget.textContent=state.starred?'★':'☆';event.currentTarget.classList.toggle('starred',state.starred);toast(state.starred?'已加入观察列表':'已移出观察列表');});
document.getElementById('refreshButton').addEventListener('click',(event)=>{const icon=event.currentTarget.querySelector('.refresh-icon');icon.animate([{transform:'rotate(0)'},{transform:'rotate(360deg)'}],{duration:600});loadDashboard();}); document.getElementById('researchButton').addEventListener('click',()=>toast('当前仅启动真实数据扫描，不生成虚构 Agent 结论')); document.getElementById('analysisButton').addEventListener('click',()=>state.selected?toast('完整分析将使用当前真实数据生成'):toast('暂无真实数据')); document.getElementById('backToOverview').addEventListener('click',()=>document.querySelector('[data-view="overview"]').click());
document.getElementById('factorRefreshButton').addEventListener('click',()=>{loadDashboard();toast('正在刷新真实因子');}); document.getElementById('mineFactorButton').addEventListener('click',runFactorMining); document.getElementById('mineRunButton').addEventListener('click',runFactorMining); document.getElementById('openMiningConfig').addEventListener('click',()=>toast('下一步配置搜索空间、评价指标和时间切分')); document.getElementById('catalogSortButton').addEventListener('click',()=>toast('当前按模型权重顺序展示真实因子'));
document.getElementById('runBacktestButton').addEventListener('click',runBacktest);
document.getElementById('agentRunButton').addEventListener('click',runAgentCollaboration);
document.getElementById('agentRefreshButton').addEventListener('click',()=>{loadDashboard();toast('正在刷新 Agent 真实运行状态');});
document.getElementById('applyUniverseButton').addEventListener('click',applyTechUniverse);
document.getElementById('applyStrategyButton').addEventListener('click',()=>{const value=document.getElementById('strategySelect').value;if(!value)return toast('请先选择一个回测策略');selectBacktestStrategy(value.split(','));});
document.querySelectorAll('.filter-button').forEach((button)=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach((item)=>item.classList.remove('active'));button.classList.add('active');if(!state.dashboard)return toast('暂无真实数据可筛选');const base=stocksForActiveSector(state.dashboard),label=button.childNodes[0].textContent.trim(),filtered=label==='可建仓'?base.filter((s)=>s.status==='可建仓'):label==='待确认'?base.filter((s)=>s.status==='等待触发'):label==='高风险'?base.filter((s)=>s.factors.volatility20>.8):base,table=document.getElementById('candidateTable');table.innerHTML=`<div class="table-row table-header"><span>证券</span><span>综合评分</span><span>真实因子</span><span>交易状态</span><span></span></div>${filtered.map(rowTemplate).join('')}`;table.querySelectorAll('.candidate-row').forEach((row)=>row.addEventListener('click',()=>selectStock(row.dataset.symbol)));toast(`已筛选 ${filtered.length} 个真实候选`);}));
loadDashboard();
